import React, { useState } from 'react';
import { motion } from 'framer-motion';
import { FileText, Download, Share2, BarChart3 } from 'lucide-react';
import { BaseCrudService } from '@/integrations';
import { ExperimentReports } from '@/entities';
import { useAstroLabStore } from '@/stores/astrolabStore';

interface ReportData {
  title: string;
  summary: string;
  conclusions: string;
  author: string;
}

export default function ExperimentReportGenerator() {
  const { selectedExperiment } = useAstroLabStore();
  const [reportData, setReportData] = useState<ReportData>({
    title: '',
    summary: '',
    conclusions: '',
    author: '',
  });
  const [isGenerating, setIsGenerating] = useState(false);
  const [generatedReport, setGeneratedReport] = useState<ExperimentReports | null>(null);

  const handleGenerateReport = async () => {
    if (!selectedExperiment) {
      alert('Please select an experiment first');
      return;
    }

    setIsGenerating(true);
    try {
      const report: ExperimentReports = {
        _id: crypto.randomUUID(),
        reportTitle: reportData.title || selectedExperiment.name,
        analysisSummary: reportData.summary,
        conclusionsFindings: reportData.conclusions,
        authorName: reportData.author,
        reportDate: new Date(),
        reportVersion: 1,
      };

      await BaseCrudService.create('experimentreports', report);
      setGeneratedReport(report);
      setReportData({ title: '', summary: '', conclusions: '', author: '' });
    } catch (error) {
      console.error('Error generating report:', error);
      alert('Failed to generate report');
    } finally {
      setIsGenerating(false);
    }
  };

  const handleExportReport = () => {
    if (!generatedReport) return;

    const reportContent = `
EXPERIMENT REPORT
=================

Title: ${generatedReport.reportTitle}
Author: ${generatedReport.authorName}
Date: ${new Date(generatedReport.reportDate as any).toLocaleDateString()}
Version: ${generatedReport.reportVersion}

ANALYSIS SUMMARY
----------------
${generatedReport.analysisSummary}

CONCLUSIONS & FINDINGS
----------------------
${generatedReport.conclusionsFindings}

Generated by AstroLab Professional Suite
    `.trim();

    const blob = new Blob([reportContent], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${generatedReport.reportTitle}-${Date.now()}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="w-full space-y-6">
      <div className="space-y-2">
        <h2 className="font-heading text-2xl font-bold text-foreground flex items-center gap-2">
          <FileText className="w-6 h-6 text-aerospace-blue" />
          Experiment Report Generator
        </h2>
        <p className="text-foreground/70 text-sm">
          Create professional reports from your experiments with analysis and conclusions
        </p>
      </div>

      {/* Selected Experiment Info */}
      {selectedExperiment ? (
        <motion.div
          initial={{ opacity: 0, y: 10 }}
          animate={{ opacity: 1, y: 0 }}
          className="p-4 bg-aerospace-blue/10 border border-aerospace-blue/30 rounded-lg"
        >
          <p className="text-sm text-foreground/80">
            <span className="font-mono text-aerospace-blue">Selected Experiment:</span>{' '}
            {selectedExperiment.name}
          </p>
          <p className="text-xs text-foreground/60 mt-1">
            {new Date(selectedExperiment.timestamp as any).toLocaleDateString()}
          </p>
        </motion.div>
      ) : (
        <div className="p-4 bg-aerospace-warning/10 border border-aerospace-warning/30 rounded-lg">
          <p className="text-sm text-aerospace-warning">
            Please select an experiment from your workspace to generate a report
          </p>
        </div>
      )}

      {/* Report Form */}
      <div className="space-y-4 p-6 bg-primary border border-secondary/20 rounded-lg">
        <div>
          <label className="block text-sm font-mono text-foreground/80 mb-2">Report Title</label>
          <input
            type="text"
            placeholder="Enter report title..."
            value={reportData.title}
            onChange={(e) => setReportData({ ...reportData, title: e.target.value })}
            className="w-full px-4 py-2 bg-primary/50 border border-secondary/30 rounded text-foreground placeholder:text-foreground/50 focus:outline-none focus:border-aerospace-blue/50"
          />
        </div>

        <div>
          <label className="block text-sm font-mono text-foreground/80 mb-2">Author Name</label>
          <input
            type="text"
            placeholder="Your name..."
            value={reportData.author}
            onChange={(e) => setReportData({ ...reportData, author: e.target.value })}
            className="w-full px-4 py-2 bg-primary/50 border border-secondary/30 rounded text-foreground placeholder:text-foreground/50 focus:outline-none focus:border-aerospace-blue/50"
          />
        </div>

        <div>
          <label className="block text-sm font-mono text-foreground/80 mb-2">Analysis Summary</label>
          <textarea
            placeholder="Describe your analysis findings..."
            value={reportData.summary}
            onChange={(e) => setReportData({ ...reportData, summary: e.target.value })}
            rows={4}
            className="w-full px-4 py-2 bg-primary/50 border border-secondary/30 rounded text-foreground placeholder:text-foreground/50 focus:outline-none focus:border-aerospace-blue/50 resize-none"
          />
        </div>

        <div>
          <label className="block text-sm font-mono text-foreground/80 mb-2">
            Conclusions & Findings
          </label>
          <textarea
            placeholder="State your conclusions..."
            value={reportData.conclusions}
            onChange={(e) => setReportData({ ...reportData, conclusions: e.target.value })}
            rows={4}
            className="w-full px-4 py-2 bg-primary/50 border border-secondary/30 rounded text-foreground placeholder:text-foreground/50 focus:outline-none focus:border-aerospace-blue/50 resize-none"
          />
        </div>

        <button
          onClick={handleGenerateReport}
          disabled={isGenerating || !selectedExperiment}
          className="w-full px-4 py-3 bg-aerospace-blue text-white font-mono font-bold rounded-lg hover:bg-aerospace-accent disabled:opacity-50 disabled:cursor-not-allowed transition-colors flex items-center justify-center gap-2"
        >
          <BarChart3 className="w-4 h-4" />
          {isGenerating ? 'Generating...' : 'Generate Report'}
        </button>
      </div>

      {/* Generated Report Preview */}
      {generatedReport && (
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          className="p-6 bg-primary border border-aerospace-blue/30 rounded-lg space-y-4"
        >
          <div className="flex items-start justify-between">
            <div>
              <h3 className="font-heading text-lg font-bold text-foreground">
                {generatedReport.reportTitle}
              </h3>
              <p className="text-xs text-foreground/60 mt-1 font-mono">
                By {generatedReport.authorName} • {new Date(generatedReport.reportDate as any).toLocaleDateString()}
              </p>
            </div>
          </div>

          <div className="space-y-4 pt-4 border-t border-secondary/20">
            <div>
              <h4 className="font-mono text-xs text-aerospace-blue uppercase tracking-wider mb-2">
                Analysis Summary
              </h4>
              <p className="text-sm text-foreground/80 leading-relaxed">
                {generatedReport.analysisSummary}
              </p>
            </div>

            <div>
              <h4 className="font-mono text-xs text-aerospace-blue uppercase tracking-wider mb-2">
                Conclusions & Findings
              </h4>
              <p className="text-sm text-foreground/80 leading-relaxed">
                {generatedReport.conclusionsFindings}
              </p>
            </div>
          </div>

          <div className="flex gap-2 pt-4 border-t border-secondary/20">
            <button
              onClick={handleExportReport}
              className="flex-1 px-4 py-2 bg-aerospace-blue text-white font-mono text-sm font-bold rounded-lg hover:bg-aerospace-accent transition-colors flex items-center justify-center gap-2"
            >
              <Download className="w-4 h-4" />
              Export Report
            </button>
            <button className="flex-1 px-4 py-2 border border-secondary/30 text-foreground font-mono text-sm font-bold rounded-lg hover:border-aerospace-blue/50 transition-colors flex items-center justify-center gap-2">
              <Share2 className="w-4 h-4" />
              Share
            </button>
          </div>
        </motion.div>
      )}
    </div>
  );
}
